# Generated by Django 5.0.1 on 2024-02-04 16:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/logos'), upload_to='')),
            ],
        ),
    ]
