#!/bin/bash

USER=lasius
PASSWORD=lasius
DATABASE=lasius
CONNECTION_LIMIT=-1;

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER $USER
WITH PASSWORD '$PASSWORD';

ALTER USER $USER CREATEDB;

CREATE DATABASE $DATABASE
  WITH OWNER = $USER
  TEMPLATE = 'template_postgis'
  CONNECTION LIMIT = $CONNECTION_LIMIT;

EOSQL
